### ISSUE TITLE
Local data does not load

### ISSUE THREAD

**Issue by martinschorb** [mobie-org/covid-em-datasets#2]
Hi,

I can't load local data:

```
(Fiji Is Just) ImageJ 2.0.0-rc-69/1.52p; Java 1.8.0_202 [64-bit]; Mac OS X 10.14.6; 182MB of 3461MB (5%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not open or parse versions file: /Volumes/emcf/common/5792_Sars-Cov-2/covid-em/data
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Could not open or parse versions file: /Volumes/emcf/common/5792_Sars-Cov-2/covid-em/data
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.UnsupportedOperationException: Could not open or parse versions file: /Volumes/emcf/common/5792_Sars-Cov-2/covid-em/data
	at de.embl.cba.mobie.dataset.DatasetsParser.datasetsFromDataSource(DatasetsParser.java:29)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:65)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by constantinpape** [comment]
@martinschorb @tischi 
I transferred this issue here, because this is not a problem with the mobie-viewer, but with this dataset.
@martinschorb
I think adding new data should work now, but I haven't fully tested it yet, and I can't find data to test it on, because the tif stacks I found were still saved with compression.

**Comment by constantinpape** [comment]
I just confirmed that this is fixed.
