### ISSUE TITLE
bookmarks

### ISSUE THREAD

**Issue by martinschorb** [mobie-org/covid-em-datasets#4]
Hi @tischi,

I put some bookmarks locally but I get:

```
[ERROR] Module threw exception
java.lang.NullPointerException
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:29)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectAdvancedCommand.run(OpenMoBIEProjectAdvancedCommand.java:22)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

What is wrong with the file? I cannot spot the problem...

```data\Covid19-S4-Area1\misc\bookmarks```

**Comment by martinschorb** [comment]
OK weird,

even if I put an empty file with `{}`, it now crashes...

**Comment by tischi** [comment]
Again: can you tell me the server? then I can have a look.
You can also send me the server by mail if you don't want to tell in public.

**Comment by martinschorb** [comment]
same local directory in the emcf common

**Comment by martinschorb** [comment]
OK, I found one dataset without the bookmarks file and added it, but it did not solve the error.

**Comment by martinschorb** [comment]
@tischer : Then I don't know what could be wrong with bookmarks in this directory that would throw this error.

**Comment by tischi** [comment]
@martinschorb 
As I wrote you by mail 14:59 today,  the layer _name_ is missing.

**Comment by martinschorb** [comment]
OK,

@constantinpape, can you check? This `default` file is created by the conversion scripts, isn't it?

I can manually update all of them, but we should make sure that new ones are in the correct format.

**Comment by constantinpape** [comment]
Yes, I think it's still missing in the updater.
I will fix it, but eventually, we need to switch to the common code-base in the python utils.

**Comment by constantinpape** [comment]
Ok, there were 2 issues:
- there was an empty file `manuscript_bookmarks.json` for each dataset; this was just a remnant of the code I have used to migrate to the new layout, I have removed these files.
- the new bookmark writer was missing something, I have added it.

Bookmarks should all work now.
