### ISSUE TITLE
AWS credentials problem...

### ISSUE THREAD

**Issue by martinschorb** [mobie-org/covid-em-datasets#7]
Hi,

when I load the remote data, I run into:

```
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.img.n5.XmlIoN5S3ImageLoader.getAwsCredentialsProvider(XmlIoN5S3ImageLoader.java:93)
	at bdv.img.n5.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:76)
	at bdv.img.n5.XmlIoN5S3ImageLoader.fromXml(XmlIoN5S3ImageLoader.java:49)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:111)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:95)
	at de.embl.cba.bdv.utils.BdvUtils.openSpimData(BdvUtils.java:1356)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:61)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:572)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:362)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:337)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:294)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
This happens with both my personal as well as the read-only credentials.

**Comment by martinschorb** [comment]
@tischer 
@constantinpape 

does it work for you now remotely? Which credentials do you use?

**Comment by constantinpape** [comment]
So for me it works (with my personal credentials), but I cannot load the latest dataset: `Covid19-S5-mock-Cell1-2`
Note that I just fixed something in the xml for this dataset, which explains why it did not work beforehand.
@tischer could you enlighten us what this java exception is trying to tell us?
It crashes with:
```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at bdv.img.n5.N5GenericImageLoader.createSetupImgLoader(N5GenericImageLoader.java:166)
	at bdv.img.n5.N5GenericImageLoader.open(N5GenericImageLoader.java:114)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:158)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:75)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:260)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:64)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:572)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:362)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:337)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:294)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by martinschorb** [comment]
Probably I am getting it because the mock dataset is the default dataset to load...
I just thought from the error message that something is wrong with the s3 auth.

**Comment by martinschorb** [comment]
So there seem to be 2 different problems...

**Comment by constantinpape** [comment]
> Probably I am getting it because the mock dataset is the default dataset to load...
> I just thought from the error message that something is wrong with the s3 auth.

Yes, there was a problem because something in the xml was missing.
I added it.
But yes, now there is another problem with the default dataset, the other datasets work.

**Comment by martinschorb** [comment]
Confirm. Get the same errors as you for the mock dataset.

When I switch to ..._5nm:

This is the switching error, I guess...
```
Adding source: sbem-6dpf-1-whole-raw...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.embl.cba.mobie.viewer.MoBIEViewer.close(MoBIEViewer.java:275)
	at de.embl.cba.mobie.viewer.ActionPanel.switchDataset(ActionPanel.java:549)
	at de.embl.cba.mobie.viewer.ActionPanel.lambda$addDatasetSelectionUI$13(ActionPanel.java:536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by constantinpape** [comment]
> This is the switching error, I guess...

Yes, exactly. I think this happens because it cannot close the previous window.

**Comment by martinschorb** [comment]
https://github.com/mobie-org/mobie/issues/9

**Comment by martinschorb** [comment]
Opened this one to improve the switching...
https://github.com/mobie-org/mobie-viewer-fiji/issues/103

**Comment by constantinpape** [comment]
@tischi to make it easier for you to check the issue at hand:
you can reproduce it by opening the covid-em project via the git url and you should then see the error below. It's most likely that this is still an issue with my converter script, but it's very hard to figure out what's going on from the error message ... 
```
Adding source: fibsem-raw...
[ERROR] Module threw exception
java.lang.NullPointerException
	at bdv.img.n5.N5GenericImageLoader.createSetupImgLoader(N5GenericImageLoader.java:166)
	at bdv.img.n5.N5GenericImageLoader.open(N5GenericImageLoader.java:114)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:158)
	at bdv.img.n5.N5GenericImageLoader.getSetupImgLoader(N5GenericImageLoader.java:75)
	at bdv.BigDataViewer.initSetupNumericType(BigDataViewer.java:260)
	at bdv.BigDataViewer.initSetups(BigDataViewer.java:292)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.initSpimData(LazySpimSource.java:64)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.wrappedVolatileSource(LazySpimSource.java:38)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:109)
	at de.embl.cba.bdv.utils.sources.LazySpimSource.getType(LazySpimSource.java:20)
	at bdv.util.BdvFunctions.addSource(BdvFunctions.java:572)
	at bdv.util.BdvFunctions.show(BdvFunctions.java:196)
	at de.embl.cba.mobie.viewer.SourcesPanel.showIntensitySource(SourcesPanel.java:387)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToViewer(SourcesPanel.java:362)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:337)
	at de.embl.cba.mobie.viewer.SourcesPanel.addSourceToPanelAndViewer(SourcesPanel.java:294)
	at de.embl.cba.mobie.bookmark.BookmarksManager.addSourcesToPanelAndViewer(BookmarksManager.java:46)
	at de.embl.cba.mobie.bookmark.BookmarksManager.setView(BookmarksManager.java:32)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:89)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:49)
	at de.embl.cba.mobie.command.OpenMoBIEProjectCommand.run(OpenMoBIEProjectCommand.java:19)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
@constantinpape @martinschorb 

The error occurs here: 

![image](https://user-images.githubusercontent.com/2157566/83773678-216eeb80-a685-11ea-8702-ebadafea3635.png)

I cannot read the data type.

`DATA_TYPE_KEY = dataType`

Seems like this file is missing:

![image](https://user-images.githubusercontent.com/2157566/83774103-993d1600-a685-11ea-9fd8-265e22ead877.png)


Does that help?

**Comment by martinschorb** [comment]
But why would that behave differently for remote and local datasets?
When load from the local drive it works.
Should I try to re-upload the data to the S3?

**Comment by constantinpape** [comment]
Wait a second, Martin. I will have a look at what's uploaded.

**Comment by martinschorb** [comment]
Got it.

the n5 folder is called differently...

I will re-upload.

**Comment by constantinpape** [comment]
yes indeed, that's the issue.

**Comment by martinschorb** [comment]
Solved. Data is accessible.
