### ISSUE TITLE
bookmarks json file encoding

### ISSUE THREAD

**Issue by martinschorb** [mobie-org/covid-em-datasets#9]
Hi,

it seems that the bookmark error Yannick was reporting (see below) is due to some weird character in the JSON file  `Covid19-S4-Area2/misc/bookmarks/bookmarks.json` ":" in line 294.

I tried getting rid of it and did not manage.

Is there a good way to copy paste text from a google doc while not introducing these?
Maybe we should ask them to add bookmarks in some other text-only way...

Is there a java tool that you could use to sanitize this? Ana additional problem was the EOL conventions in the file (Windows vs. Unix).

```
Adding source: fibsem-raw...
Exception in thread "AWT-EventQueue-0" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 294 column 2 path $.
	at com.google.gson.Gson.fromJson(Gson.java:942)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.readBookmarksFromFile(BookmarksJsonParser.java:136)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.parseBookmarks(BookmarksJsonParser.java:120)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.readBookmarks(BookmarksJsonParser.java:105)
	at de.embl.cba.mobie.bookmark.BookmarksJsonParser.getBookmarks(BookmarksJsonParser.java:40)
	at de.embl.cba.mobie.viewer.MoBIEViewer.fetchBookmarks(MoBIEViewer.java:182)
	at de.embl.cba.mobie.viewer.MoBIEViewer.<init>(MoBIEViewer.java:77)
	at de.embl.cba.mobie.viewer.ActionPanel.switchDataset(ActionPanel.java:548)
	at de.embl.cba.mobie.viewer.ActionPanel.lambda$addDatasetSelectionUI$13(ActionPanel.java:536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 294 column 2 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	... 44 more
```

**Comment by martinschorb** [comment]
OK, got the character issue solved.
I don't know if the EOL convention still is a problem when parsing JSON. But in the github UI the file was shown as corrupted when it had some Windows-style EOLs.

**Comment by martinschorb** [comment]
Still doesn't work.

I am trying to find out what is wrong with that file.
Let me know if you spot something...

**Comment by martinschorb** [comment]
The problem is in this entry:

```
,

"Centrioloid / Lysosomes cross-section":
 { "position": [22.46451488195762,
8.313477943040741,
32.402837451681144],
 "view": [ -35.22555382568819,
 -111.23190501880107,
 246.08708640418263,
 -5738.870892633966,
 -269.841753854379,
 4.564794718130589,
 -36.562562236687846,
 7686.645536003927,
 10.808268399882104,
 -248.5535282115453,
 -110.79961813619371,
 5413.763784309719

]
}
```

what the hell is wrong there...?

**Comment by martinschorb** [comment]
OK, fuck...

There is a delay of a few minutes in the github API or the way you call things. 
It is not using the most recent commit.
This is not very helpful in debugging...

I would need an option to use remote images but local bookmarks, so I can check things effectively.
For now it looks like the problem is some characters not supported in the name (probably `/`). But I cannot really test it more.

**Comment by martinschorb** [comment]
Good,
set up a test environment entirely locally and here this exact JSON is parsed correctly. WTH is going on?

**Comment by martinschorb** [comment]
OK,

it seems to be a problem with github and the way the JSON file is handed over to MoBIE.

The identical JSON file is opened correctly from local storage but fails when opened through github.

**Comment by martinschorb** [comment]
There's nothing more I can do to find the problem. It is either the character in the JSON name key or the length of that string. But only in combination with github...

@tischer , @constantinpape  do you have an idea?

**Comment by constantinpape** [comment]
@martinschorb
I just loaded the bookmark `Covid19-S4-Area2` -> `Centroloid / ...` and it works for me.
Indeed there is some delay on github when refreshing the raw data representations, so that might explain it. In general, we should make the bookmark adding more streamlined so that these encoding issues are not happening. 
Ideally, we would add it through the viewer UI, but that will take a while.
We could also add a small wizard to `mobie-utils-python` to do this.
@martinschorb do you have any opinions on how to make this easier?

**Comment by tischi** [comment]
I think a small python tool would be the way to do it for now!

**Comment by martinschorb** [comment]
@constantinpape 
Did you load it from github?
I still get:
```
Adding source: sbem-6dpf-1-whole-raw...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at de.embl.cba.mobie.viewer.MoBIEViewer.close(MoBIEViewer.java:275)
	at de.embl.cba.mobie.viewer.ActionPanel.switchDataset(ActionPanel.java:549)
	at de.embl.cba.mobie.viewer.ActionPanel.lambda$addDatasetSelectionUI$13(ActionPanel.java:536)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

when I load the same json locally, it loads.

**Comment by martinschorb** [comment]
ah, wait. That's the switch issue...

**Comment by constantinpape** [comment]
@tischi I agree, a small python tool is the way to go. I will see what I can cook up. This would be a CLI first, if someone wants a GUI for it they need to write it themselves ;P.

@martinschorb yes, I loaded from github and it worked fine.

**Comment by martinschorb** [comment]
Could you just make MoBIE  write the log into a text file.
We would then take it from there.

We would only need some way of giving the bookmark a name.

**Comment by martinschorb** [comment]
OK, works now with complete bookmarks file.
